name: release-liquidity

on:
  push:
    tags:
      - 'release-liquidity-*'
    branches:
      - 'liquidity-synthetix-eth'
      - 'releases'

jobs:
  release-liquidity:
    runs-on: ubuntu-latest
    steps:
      - run: git config --global user.email engineering@snxdao.io
      - run: git config --global user.name synthetix-team

      - uses: actions/checkout@v4
        with:
          path: liquidity
          repository: 'Synthetixio/liquidity.synthetix.eth'
          ref: 'master'
          ssh-key: '${{ secrets.LIQUIDITY_SSH_KEY }}'

      - uses: actions/checkout@v4
        with:
          path: v3ui
          ref: '${{ github.sha }}'
          ssh-key: '${{ secrets.V3UI_SSH_KEY }}'

      - run: yarn workspaces focus @snx-v3/liquidity
        working-directory: v3ui

      - run: yarn workspace @snx-v3/liquidity build
        working-directory: v3ui

      - run: rm -rf ./liquidity/*
      - run: cp -r ./v3ui/liquidity/ui/dist/* ./liquidity/

      - run: git add .
        working-directory: liquidity

      - run: |
          git commit -m "Release ${{ github.event.release.name }}" \
            --allow-empty \
            -m "Source: ${{ github.server_url}}/${{ github.repository }}" \
            -m "Commit: ${{ github.sha }}"
        working-directory: liquidity

      - run: git push origin master
        working-directory: liquidity
