name: release-website

on:
  push:
    tags:
      - 'release-website-*'
    branches:
      - 'v3-synthetix-eth'

jobs:
  release-website:
    # Should be good without checks, we wouldn't release smth that's broken
    # if: ${{ github.event.check_suite.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - run: git config --global user.email engineering@snxdao.io
      - run: git config --global user.name synthetix-team

      - uses: actions/checkout@v4
        with:
          path: website
          repository: 'Synthetixio/v3.synthetix.eth'
          ref: 'master'
          ssh-key: '${{ secrets.V3_WEBSITE_DEPLOYER_SSH_PRIVATE_KEY }}'

      - uses: actions/checkout@v4
        with:
          path: v3ui
          ref: '${{ github.sha }}'
          ssh-key: '${{ secrets.SSH_PRIVATE_KEY }}'

      - run: yarn workspaces focus @snx-v3/website
        working-directory: v3ui

      - run: yarn workspace @snx-v3/website build
        working-directory: v3ui

      - run: rm -rf ./website/*
      - run: cp ./v3ui/website/ui/_redirects ./website/_redirects
      - run: cp ./v3ui/website/ui/favicon.ico ./website/favicon.ico
      - run: cp ./v3ui/website/ui/index.html ./website/index.html
      - run: cp -r ./v3ui/website/ui/dist ./website/

      - run: git add .
        working-directory: website

      - run: |
          git commit -m "Release ${{ github.event.release.name }}" \
            --allow-empty \
            -m "Source: ${{ github.server_url}}/${{ github.repository }}" \
            -m "Commit: ${{ github.sha }}"
        working-directory: website

      - run: git push origin master
        working-directory: website
