name: release-governance

on:
  push:
    tags:
      - 'release-governance-*'
    branches:
      - 'governance-synthetix-eth'
      - 'releases'

jobs:
  release-governance:
    runs-on: ubuntu-latest
    steps:
      - run: git config --global user.email engineering@snxdao.io
      - run: git config --global user.name synthetix-team

      - uses: actions/checkout@v4
        with:
          path: governance
          repository: 'Synthetixio/governance.synthetix.eth'
          ref: 'master'
          ssh-key: '${{ secrets.GOVERNANCE_SSH_KEY }}'

      - uses: actions/checkout@v4
        with:
          path: v3ui
          ref: '${{ github.sha }}'
          ssh-key: '${{ secrets.V3UI_SSH_KEY }}'

      - run: yarn workspaces focus @snx-v3/governance
        working-directory: v3ui

      - run: yarn workspace @snx-v3/governance build
        working-directory: v3ui

      - run: rm -rf ./governance/*

      - run: git checkout HEAD -- CNAME || true
        working-directory: governance

      - run: cp -r ./v3ui/governance/ui/dist/* ./governance/

      - run: git add .
        working-directory: governance

      - run: |
          git commit -m "Release ${{ github.event.release.name }}" \
            --allow-empty \
            -m "Source: ${{ github.server_url}}/${{ github.repository }}" \
            -m "Commit: ${{ github.sha }}"
        working-directory: governance

      - run: git push origin master
        working-directory: governance
