name: release-ultrasound

on:
  push:
    tags:
      - 'release-ultrasound-*'
    branches:
      - 'release-ultrasound'
      - 'releases'

jobs:
  release-liquidity:
    runs-on: ubuntu-latest
    steps:
      - run: git config --global user.email engineering@snxdao.io
      - run: git config --global user.name synthetix-team

      - uses: actions/checkout@v4
        with:
          path: ultrasound
          repository: 'Synthetixio/ultrasound.homes'
          ref: 'master'
          ssh-key: '${{ secrets.ULTRASOUND_SSH_KEY }}'

      - uses: actions/checkout@v4
        with:
          path: v3ui
          ref: '${{ github.sha }}'
          ssh-key: '${{ secrets.V3UI_SSH_KEY }}'

      - run: yarn workspaces focus @snx-v3/ultrasound
        working-directory: v3ui

      - run: yarn workspace @snx-v3/ultrasound build
        working-directory: v3ui

      - run: rm -rf ./ultrasound/*

      - run: git checkout HEAD -- CNAME || true
        working-directory: ultrasound

      - run: cp -r ./v3ui/ultrasound/ui/dist/* ./ultrasound/

      - run: git add .
        working-directory: ultrasound

      - run: |
          git commit -m "Release ${{ github.event.release.name }}" \
            --allow-empty \
            -m "Source: ${{ github.server_url}}/${{ github.repository }}" \
            -m "Commit: ${{ github.sha }}"
        working-directory: ultrasound

      - run: git push origin master
        working-directory: ultrasound
